apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app
  labels:
    app: todo-app
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30080
    protocol: TCP
    name: http
  sessionAffinity: None
